### ISSUE TITLE
Corrupted report when printing to report.maxY() - report.heightOfString()

### ISSUE THREAD

**Issue by gillsonkell** [NathanaelA/fluentreports#151] opened 2020-02-18 23:11 UTC
```
const Report = require('./fluentreports/lib/fluentReports.js').Report;

new Report()
  .groupBy()
  .header((report) => {
    report.print('Header');
  })
  .detail((report, data) => {
    report.print('Detail', {
      y: report.maxY() - report.heightOfString()
    });
  })
  .data({})
  .render((error) => {
    if (error) {
      throw error;
    }
  });
```
This code unexpectedly results in a corrupted PDF. It works fine if the Y is slightly greater than or less than the given value.

Also, when you add a page footer, the result is a missing header instead of a corrupted PDF:
```
const Report = require('./fluentreports/lib/fluentReports.js').Report;

new Report()
  .groupBy()
  .header((report) => {
    report.print('Header');
  })
  .detail((report, data) => {
    report.print('Detail', {
      y: report.maxY() - report.heightOfString()
    });
  })
  .pageFooter((report) => {
    report.print('Footer');
  })
  .data({})
  .render((error) => {
    if (error) {
      throw error;
    }
  });
```
In this case the second page will say "Footer", but not "Header" as expected.

**Comment by NathanaelA** [comment] 2020-03-02 10:53
This was fixed with the same fix as #152 
On your second part of this issue; second page would NOT have a header unless you changed this to a "pageHeader".   Otherwise the "header" is just the first header of the null group; not a header that is repeated because their is no grouping...

**Closed by NathanaelA** 2020-03-02 10:53 UTC

**Comment by gillsonkell** [comment] 2020-03-02 13:48
Thanks, sir! I've actually found that having a `header()` with an empty `groupBy()` does repeat on each page, and I take advantage of that in some of my reports. So, for example:
```
const Report = require('./fluentreports/lib/fluentReports.js').Report;

new Report()
  .groupBy()
  .header((report) => {
    report.print('Header');
  })
  .detail((report, data) => {
    report.print('Page 1');
    report.addY(1000);
    report.print('Page 2');
  })
  .data({})
  .render((error) => {
    if (error) {
      throw error;
    }
  });
```
Will have two pages, "Header" on each of them.

**Comment by NathanaelA** [comment] 2020-03-02 15:16
Ah, that is an interesting side effect  you found; grouping on `undefined`...   
However, again in the second case; the reason it doesn't show up is because it is the final summary footer; which has no grouping.   By default the system paged on page 1 from your code.  Then realized it was done with all data; and needed to print the final footer.    In your case the final footer is the same as the normal footer; so you get a page with the final footer.    The final footer is printed (even if it is the standard footer) with the "isFinal" state set so that you can do whatever you want as a "final" footer.

One thing that I thought about after I traced the behavior; was maybe we should add a flag to say ignore the standard footer (the isFinal flag triggers nothing); if it is the only thing to left to print....    Or depreciate the isFinal flag; and just treat the finalSummary as the only valid last footer in this case...

At this moment; the engine is working as designed...
